<?php
/**
 * Cartly DS — stylesheet compiler.
 *
 * Turns the design tokens + component layer into a single, self-contained,
 * distributable CSS file. Unlike the old Tailwind pipeline this needs no Node
 * and no framework: it just needs PHP. The output is the canonical stylesheet
 * both the WordPress site and the React storefront can consume as a drop-in.
 *
 * @package CartlyDS
 */

namespace CartlyDS;

final class Compiler
{
	/** @var Tokens */
	private Tokens $tokens;

	/**
	 * @param Tokens $tokens Parsed design tokens.
	 */
	public function __construct( Tokens $tokens ) {
		$this->tokens = $tokens;
	}

	/**
	 * Compile to CSS.
	 *
	 * @param bool $minify Strip comments and collapse whitespace.
	 * @return string
	 */
	public function compile( bool $minify = false ): string {
		$css  = $this->tokenCss();
		$css .= "\n\n" . $this->componentCss();

		if ( $minify ) {
			return $this->minify( $css );
		}
		return $css;
	}

	/**
	 * Re-emit the custom-property block for both colour schemes.
	 *
	 * @return string
	 */
	private function tokenCss(): string {
		$light = $this->emitVarBlock( $this->tokens->schemeVars( 'light' ), 'root' );
		$dark  = $this->emitVarBlock( $this->tokens->schemeVars( 'dark' ), 'dark' );

		return "/* Cartly DS — design tokens. Generated by bin/cartly. */\n" . $light . "\n\n" . $dark;
	}

	/**
	 * Emit one rule block of custom properties.
	 *
	 * @param array<string,string> $vars     Custom properties for the scheme.
	 * @param string               $selector 'root' or 'dark'.
	 * @return string
	 */
	private function emitVarBlock( array $vars, string $selector ): string {
		$lines = array();
		foreach ( $vars as $name => $value ) {
			$lines[] = "\t--{$name}: {$value};";
		}
		$lines[] = 'dark' === $selector ? "\tcolor-scheme: dark;" : "\tcolor-scheme: light;";
		$rule = 'dark' === $selector ? '.dark' : ':root';
		return "{$rule} {\n" . implode( "\n", $lines ) . "\n}";
	}

	/**
	 * The component layer (verbatim from assets/src/components.css).
	 *
	 * @return string
	 */
	private function componentCss(): string {
		$path = dirname( __DIR__, 1 ) . '/assets/src/components.css';
		if ( is_file( $path ) ) {
			$css = file_get_contents( $path );
			if ( false !== $css ) {
				return trim( $css );
			}
		}
		return '';
	}

	/**
	 * Lightweight CSS minifier (comments + whitespace collapsing).
	 *
	 * @param string $css
	 * @return string
	 */
	private function minify( string $css ): string {
		$css = preg_replace( '!/\*.*?\*/!s', '', $css );
		$css = preg_replace( '/\s+/', ' ', $css );
		$css = preg_replace( '/\s*([{}:;,>+])\s*/', '$1', $css );
		$css = preg_replace( '/;}/', '}', $css );
		return trim( $css );
	}
}
